version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpsite
    deploy: 
      placement: 
        constraints:
          - node.labels.node_number==4

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
    deploy: 
      placement: 
        constraints:
          - node.labels.node_number==4

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes: 
      - wordpress:/var/www/html
    networks:
      - wpsite
    deploy: 
      placement: 
        constraints:
          - node.labels.node_number==4
    
  client:
   image: luongquocdat01091995/httpd-application:client
    environment: 
        - SERVER_IP=192.168.2.83
        - SERVER_PORT=8080
    deploy: 
      placement: 
        constraints:
          - node.labels.node_number==4

networks:
  wpsite:
volumes:
  db_data:
  wordpress: